# Generated by Django 4.2.2 on 2023-06-16 19:31

import car_collection.cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Sports Car', 'Sports Car'), ('Other', 'Other'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus')], verbose_name='Type')),
                ('car_model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Model')),
                ('year', models.IntegerField(validators=[car_collection.cars.models.year_is_valid])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
